=== ptidejteam/P-MARt/Xalan v1.0.0/xdocs/style/dtd/javadocpackages.dtd
<?xml encoding='US-ASCII'?>

<!-- JAVADOC PACKAGES DTD -->

<!-- import the external source-specific dtd -->
<!ENTITY % externalEntity SYSTEM "sbk:/sources/entities.ent">
%externalEntity;

<!ELEMENT javadocPackages (resources?| home| package)+>
<!ATTLIST javadocPackages source  CDATA #REQUIRED
                          target  CDATA #IMPLIED>

<!ELEMENT resources EMPTY>
<!ATTLIST resources source CDATA #REQUIRED>

<!ELEMENT home EMPTY>
<!ATTLIST home           source  CDATA #REQUIRED
                         target  CDATA #REQUIRED>

<!ELEMENT package EMPTY>
<!ATTLIST package         source  CDATA #REQUIRED
                          target  CDATA #REQUIRED>

=== ptidejteam/P-MARt/Xalan v1.0.0/xdocs/sources/javadocPackages.xml
<?xml version="1.0"?>
<!DOCTYPE javadocPackages SYSTEM "sbk:/style/dtd/javadocPackages.dtd">

<javadocPackages source="xalan" target="../src">
  <resources source="sbk:sources/xalan/resources.xml"/>
  <home source="xalan/javadocOverview.xml" target="javadocOverview.html"/>
  <package source="xalan/org-apache-xalan-xpath.xml" target="org/apache/xalan/xpath/package.html"/>
  <package source="xalan/org-apache-xalan-xpath-xdom.xml" target="org/apache/xalan/xpath/xdom/package.html"/>
  <package source="xalan/org-apache-xalan-xpath-dtm.xml" target="org/apache/xalan/xpath/dtm/package.html"/>
  <package source="xalan/org-apache-xalan-xpath-xml.xml" target="org/apache/xalan/xpath/xml/package.html"/>
  <package source="xalan/org-apache-xalan-xslt.xml" target="org/apache/xalan/xslt/package.html"/>
  <package source="xalan/org-apache-xalan-xslt-trace.xml" target="org/apache/xalan/xslt/trace/package.html"/>
  <package source="xalan/org-apache-xalan-xslt-client.xml" target="org/apache/xalan/xslt/client/package.html"/>
  <package source="xalan/org-apache-xalan-xslt-extensions.xml" target="org/apache/xalan/xslt/extensions/package.html"/>
</javadocPackages>
